using Text_Grab.Interfaces;
using Text_Grab.Properties;
using Text_Grab.Services;

namespace Tests;

/// <summary>
/// Guards the seam that lets Text-Grab.Core read settings without referencing the app.
/// If these break, portable code either cannot reach settings or is silently reading the wrong
/// instance - both of which surface far away from the actual cause.
/// </summary>
[Collection("Settings isolation")]
public class SettingsAccessTests
{
    [Fact]
    public void ModuleInitializer_RegistersAResolverWithoutAnyStartupCall()
    {
        // The test host never raises App's WPF Startup event, so this passing is the proof that
        // wiring lives in a module initializer and not in appStartup.
        Assert.True(SettingsAccess.IsConfigured);
    }

    [Fact]
    public void Current_ResolvesToTheAppSettingsObject()
    {
        ITextGrabSettings settings = SettingsAccess.Current;

        Assert.IsType<Settings>(settings);
    }

    [Fact]
    public void GeneratedSettingsPropertiesSatisfyTheInterfaceWithoutForwarding()
    {
        // Settings.Designer.cs is regenerated by SettingsSingleFileGenerator. Reading and writing
        // through the interface here is what catches a generated property being renamed or having
        // its type changed out from under ITextGrabSettings.
        ITextGrabSettings settings = new Settings();

        settings.CorrectToLatin = true;
        settings.ParagraphDetection = false;
        settings.TesseractPath = @"C:\tesseract\tesseract.exe";
        settings.LastUsedLang = "ja-JP";

        Assert.True(settings.CorrectToLatin);
        Assert.False(settings.ParagraphDetection);
        Assert.Equal(@"C:\tesseract\tesseract.exe", settings.TesseractPath);
        Assert.Equal("ja-JP", settings.LastUsedLang);
    }

    [Fact]
    public void SetResolver_SubstitutesAFakeAndCanBeRestored()
    {
        Settings substitute = new() { CorrectErrors = false, RemoveFurigana = true };

        try
        {
            SettingsAccess.SetResolver(() => substitute);

            Assert.Same(substitute, SettingsAccess.Current);
            Assert.False(SettingsAccess.Current.CorrectErrors);
            Assert.True(SettingsAccess.Current.RemoveFurigana);
        }
        finally
        {
            SettingsAccess.SetResolver(static () => Text_Grab.Utilities.AppUtilities.TextGrabSettings);
        }

        Assert.NotSame(substitute, SettingsAccess.Current);
    }

    [Fact]
    public void Current_ThrowsAClearErrorWhenNoResolverIsRegistered()
    {
        try
        {
            SettingsAccess.ClearResolver();

            InvalidOperationException ex = Assert.Throws<InvalidOperationException>(() => SettingsAccess.Current);
            Assert.Contains(nameof(SettingsAccess.SetResolver), ex.Message);
        }
        finally
        {
            SettingsAccess.SetResolver(static () => Text_Grab.Utilities.AppUtilities.TextGrabSettings);
        }
    }
}
