<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Platforms>x64;x86;ARM64</Platforms>
        <WindowsSdkPackageVersion>10.0.22621.48</WindowsSdkPackageVersion>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\..\Tests\Images\font_sample.png" Link="Images\font_sample.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Tests\Images\paragraph-test-image.png" Link="Images\paragraph-test-image.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Tests\Images\Ja-Lang-Image.png" Link="Images\Ja-Lang-Image.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Tests\Images\QrCodeTestImage.png" Link="Images\QrCodeTestImage.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\..\Tests\Images\Table-Test.png" Link="Images\Table-Test.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
