name: "build new release"

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: "Text-Grab/Text-Grab.csproj"
  TEST_PATH: "Tests/Tests.csproj"


jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
